name: spot_a_camp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_styled_toast: ^2.2.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.0.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_gen_runner:

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/